name: ijepa_py310
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.5.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - cpuonly=2.0
  - expat=2.6.4
  - ffmpeg=5.1.2
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.21.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - icu=72.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jasper=2.0.33
  - jinja2=3.1.6
  - jpeg=9e
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libiconv=1.18
  - libidn2=2.3.4
  - libintl=0.23.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.52.0
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvpx=1.11.0
  - libwebp-base=1.3.2
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.8.1
  - networkx=3.4.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openssl=3.4.1
  - p11-kit=0.24.1
  - pcre2=10.43
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.40.0
  - py-opencv=4.7.0
  - pysocks=1.7.1
  - python=3.10.16
  - python_abi=3.10
  - pytorch=2.0.0
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - sqlite=3.45.3
  - svt-av1=1.4.1
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchvision=0.15.0
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.5.2
      - cloudpickle==3.1.1
      - fsspec==2025.3.0
      - huggingface-hub==0.29.3
      - packaging==24.2
      - psutil==7.0.0
      - regex==2024.11.6
      - safetensors==0.5.3
      - submitit==1.5.2
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - transformers==4.49.0
